/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AlbumType = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'trackList' : IDL.Vec(IDL.Text),
  'year' : IDL.Nat,
  'description' : IDL.Text,
});
export const MemberType = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'years' : IDL.Tuple(IDL.Nat, IDL.Opt(IDL.Nat)),
});
export const PhotoType = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
});
export const PressType = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'date' : Time,
  'excerpt' : IDL.Text,
  'publication' : IDL.Text,
});
export const ShowType = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'setlist' : IDL.Vec(IDL.Text),
  'venue' : IDL.Text,
  'city' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
});
export const SongType = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'album' : IDL.Text,
  'lyrics' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
});
export const VideoType = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
});
export const RelatedType = IDL.Variant({
  'members' : IDL.Vec(MemberType),
  'albums' : IDL.Vec(AlbumType),
  'shows' : IDL.Vec(ShowType),
  'songs' : IDL.Vec(SongType),
  'press' : IDL.Vec(PressType),
  'videos' : IDL.Vec(VideoType),
  'photos' : IDL.Vec(PhotoType),
});
export const RelatedItem = IDL.Record({ 'relatedType' : RelatedType });
export const Related = IDL.Record({
  'id' : IDL.Text,
  'relatedItems' : IDL.Vec(RelatedItem),
  'relatedType' : RelatedType,
});

export const idlService = IDL.Service({
  'createAlbum' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'createMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'createPhoto' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'createPress' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createShow' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'createSong' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'deleteAlbum' : IDL.Func([IDL.Text], [], []),
  'deleteMember' : IDL.Func([IDL.Text], [], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'deletePress' : IDL.Func([IDL.Text], [], []),
  'deleteShow' : IDL.Func([IDL.Text], [], []),
  'deleteSong' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getAlbum' : IDL.Func([IDL.Text], [AlbumType], ['query']),
  'getAllAlbums' : IDL.Func([], [IDL.Vec(AlbumType)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(MemberType)], ['query']),
  'getAllPhotos' : IDL.Func([], [IDL.Vec(PhotoType)], ['query']),
  'getAllPress' : IDL.Func([], [IDL.Vec(PressType)], ['query']),
  'getAllShows' : IDL.Func([], [IDL.Vec(ShowType)], ['query']),
  'getAllSongs' : IDL.Func([], [IDL.Vec(SongType)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(VideoType)], ['query']),
  'getMember' : IDL.Func([IDL.Text], [MemberType], ['query']),
  'getPhoto' : IDL.Func([IDL.Text], [PhotoType], ['query']),
  'getPress' : IDL.Func([IDL.Text], [PressType], ['query']),
  'getRelated' : IDL.Func([IDL.Text], [Related], ['query']),
  'getShow' : IDL.Func([IDL.Text], [ShowType], ['query']),
  'getSong' : IDL.Func([IDL.Text], [SongType], ['query']),
  'getVideo' : IDL.Func([IDL.Text], [VideoType], ['query']),
  'updateAlbum' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'updatePhoto' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updatePress' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateShow' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateSong' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AlbumType = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'trackList' : IDL.Vec(IDL.Text),
    'year' : IDL.Nat,
    'description' : IDL.Text,
  });
  const MemberType = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'years' : IDL.Tuple(IDL.Nat, IDL.Opt(IDL.Nat)),
  });
  const PhotoType = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
  });
  const PressType = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'date' : Time,
    'excerpt' : IDL.Text,
    'publication' : IDL.Text,
  });
  const ShowType = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'setlist' : IDL.Vec(IDL.Text),
    'venue' : IDL.Text,
    'city' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
  });
  const SongType = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'album' : IDL.Text,
    'lyrics' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
  });
  const VideoType = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
  });
  const RelatedType = IDL.Variant({
    'members' : IDL.Vec(MemberType),
    'albums' : IDL.Vec(AlbumType),
    'shows' : IDL.Vec(ShowType),
    'songs' : IDL.Vec(SongType),
    'press' : IDL.Vec(PressType),
    'videos' : IDL.Vec(VideoType),
    'photos' : IDL.Vec(PhotoType),
  });
  const RelatedItem = IDL.Record({ 'relatedType' : RelatedType });
  const Related = IDL.Record({
    'id' : IDL.Text,
    'relatedItems' : IDL.Vec(RelatedItem),
    'relatedType' : RelatedType,
  });
  
  return IDL.Service({
    'createAlbum' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'createMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'createPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'createPress' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createShow' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'createSong' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'deleteAlbum' : IDL.Func([IDL.Text], [], []),
    'deleteMember' : IDL.Func([IDL.Text], [], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'deletePress' : IDL.Func([IDL.Text], [], []),
    'deleteShow' : IDL.Func([IDL.Text], [], []),
    'deleteSong' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getAlbum' : IDL.Func([IDL.Text], [AlbumType], ['query']),
    'getAllAlbums' : IDL.Func([], [IDL.Vec(AlbumType)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(MemberType)], ['query']),
    'getAllPhotos' : IDL.Func([], [IDL.Vec(PhotoType)], ['query']),
    'getAllPress' : IDL.Func([], [IDL.Vec(PressType)], ['query']),
    'getAllShows' : IDL.Func([], [IDL.Vec(ShowType)], ['query']),
    'getAllSongs' : IDL.Func([], [IDL.Vec(SongType)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(VideoType)], ['query']),
    'getMember' : IDL.Func([IDL.Text], [MemberType], ['query']),
    'getPhoto' : IDL.Func([IDL.Text], [PhotoType], ['query']),
    'getPress' : IDL.Func([IDL.Text], [PressType], ['query']),
    'getRelated' : IDL.Func([IDL.Text], [Related], ['query']),
    'getShow' : IDL.Func([IDL.Text], [ShowType], ['query']),
    'getSong' : IDL.Func([IDL.Text], [SongType], ['query']),
    'getVideo' : IDL.Func([IDL.Text], [VideoType], ['query']),
    'updateAlbum' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'updatePhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updatePress' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateShow' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateSong' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };