/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlbumType {
  'id' : string,
  'title' : string,
  'trackList' : Array<string>,
  'year' : bigint,
  'description' : string,
}
export interface MemberType {
  'id' : string,
  'bio' : string,
  'name' : string,
  'role' : string,
  'years' : [bigint, [] | [bigint]],
}
export interface PhotoType {
  'id' : string,
  'url' : string,
  'title' : string,
  'year' : bigint,
  'description' : string,
}
export interface PressType {
  'id' : string,
  'url' : string,
  'title' : string,
  'date' : Time,
  'excerpt' : string,
  'publication' : string,
}
export interface Related {
  'id' : string,
  'relatedItems' : Array<RelatedItem>,
  'relatedType' : RelatedType,
}
export interface RelatedItem { 'relatedType' : RelatedType }
export type RelatedType = { 'members' : Array<MemberType> } |
  { 'albums' : Array<AlbumType> } |
  { 'shows' : Array<ShowType> } |
  { 'songs' : Array<SongType> } |
  { 'press' : Array<PressType> } |
  { 'videos' : Array<VideoType> } |
  { 'photos' : Array<PhotoType> };
export interface ShowType {
  'id' : string,
  'title' : string,
  'setlist' : Array<string>,
  'venue' : string,
  'city' : string,
  'date' : Time,
  'description' : string,
}
export interface SongType {
  'id' : string,
  'title' : string,
  'duration' : bigint,
  'album' : string,
  'lyrics' : string,
  'year' : bigint,
  'description' : string,
}
export type Time = bigint;
export interface VideoType {
  'id' : string,
  'url' : string,
  'title' : string,
  'year' : bigint,
  'description' : string,
}
export interface _SERVICE {
  'createAlbum' : ActorMethod<
    [string, string, bigint, string, Array<string>],
    undefined
  >,
  'createMember' : ActorMethod<
    [string, string, string, string, bigint, [] | [bigint]],
    undefined
  >,
  'createPhoto' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
  'createPress' : ActorMethod<
    [string, string, string, Time, string, string],
    undefined
  >,
  'createShow' : ActorMethod<
    [string, string, Time, string, string, string, Array<string>],
    undefined
  >,
  'createSong' : ActorMethod<
    [string, string, string, bigint, bigint, string, string],
    undefined
  >,
  'createVideo' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
  'deleteAlbum' : ActorMethod<[string], undefined>,
  'deleteMember' : ActorMethod<[string], undefined>,
  'deletePhoto' : ActorMethod<[string], undefined>,
  'deletePress' : ActorMethod<[string], undefined>,
  'deleteShow' : ActorMethod<[string], undefined>,
  'deleteSong' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getAlbum' : ActorMethod<[string], AlbumType>,
  'getAllAlbums' : ActorMethod<[], Array<AlbumType>>,
  'getAllMembers' : ActorMethod<[], Array<MemberType>>,
  'getAllPhotos' : ActorMethod<[], Array<PhotoType>>,
  'getAllPress' : ActorMethod<[], Array<PressType>>,
  'getAllShows' : ActorMethod<[], Array<ShowType>>,
  'getAllSongs' : ActorMethod<[], Array<SongType>>,
  'getAllVideos' : ActorMethod<[], Array<VideoType>>,
  'getMember' : ActorMethod<[string], MemberType>,
  'getPhoto' : ActorMethod<[string], PhotoType>,
  'getPress' : ActorMethod<[string], PressType>,
  'getRelated' : ActorMethod<[string], Related>,
  'getShow' : ActorMethod<[string], ShowType>,
  'getSong' : ActorMethod<[string], SongType>,
  'getVideo' : ActorMethod<[string], VideoType>,
  'updateAlbum' : ActorMethod<
    [string, string, bigint, string, Array<string>],
    undefined
  >,
  'updateMember' : ActorMethod<
    [string, string, string, string, bigint, [] | [bigint]],
    undefined
  >,
  'updatePhoto' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
  'updatePress' : ActorMethod<
    [string, string, string, Time, string, string],
    undefined
  >,
  'updateShow' : ActorMethod<
    [string, string, Time, string, string, string, Array<string>],
    undefined
  >,
  'updateSong' : ActorMethod<
    [string, string, string, bigint, bigint, string, string],
    undefined
  >,
  'updateVideo' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];