/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PhotoType {
    id: string;
    url: string;
    title: string;
    year: bigint;
    description: string;
}
export interface RelatedItem {
    relatedType: RelatedType;
}
export type Time = bigint;
export interface SongType {
    id: string;
    title: string;
    duration: bigint;
    album: string;
    lyrics: string;
    year: bigint;
    description: string;
}
export interface AlbumType {
    id: string;
    title: string;
    trackList: Array<string>;
    year: bigint;
    description: string;
}
export interface MemberType {
    id: string;
    bio: string;
    name: string;
    role: string;
    years: [bigint, bigint | null];
}
export interface PressType {
    id: string;
    url: string;
    title: string;
    date: Time;
    excerpt: string;
    publication: string;
}
export interface Related {
    id: string;
    relatedItems: Array<RelatedItem>;
    relatedType: RelatedType;
}
export interface VideoType {
    id: string;
    url: string;
    title: string;
    year: bigint;
    description: string;
}
export interface ShowType {
    id: string;
    title: string;
    setlist: Array<string>;
    venue: string;
    city: string;
    date: Time;
    description: string;
}
export type RelatedType = {
    __kind__: "members";
    members: Array<MemberType>;
} | {
    __kind__: "albums";
    albums: Array<AlbumType>;
} | {
    __kind__: "shows";
    shows: Array<ShowType>;
} | {
    __kind__: "songs";
    songs: Array<SongType>;
} | {
    __kind__: "press";
    press: Array<PressType>;
} | {
    __kind__: "videos";
    videos: Array<VideoType>;
} | {
    __kind__: "photos";
    photos: Array<PhotoType>;
};
export interface backendInterface {
    createAlbum(id: string, title: string, year: bigint, description: string, trackList: Array<string>): Promise<void>;
    createMember(id: string, name: string, role: string, bio: string, startYear: bigint, endYear: bigint | null): Promise<void>;
    createPhoto(id: string, title: string, url: string, description: string, year: bigint): Promise<void>;
    createPress(id: string, title: string, publication: string, date: Time, url: string, excerpt: string): Promise<void>;
    createShow(id: string, title: string, date: Time, venue: string, city: string, description: string, setlist: Array<string>): Promise<void>;
    createSong(id: string, title: string, album: string, year: bigint, duration: bigint, lyrics: string, description: string): Promise<void>;
    createVideo(id: string, title: string, url: string, description: string, year: bigint): Promise<void>;
    deleteAlbum(id: string): Promise<void>;
    deleteMember(id: string): Promise<void>;
    deletePhoto(id: string): Promise<void>;
    deletePress(id: string): Promise<void>;
    deleteShow(id: string): Promise<void>;
    deleteSong(id: string): Promise<void>;
    deleteVideo(id: string): Promise<void>;
    getAlbum(id: string): Promise<AlbumType>;
    getAllAlbums(): Promise<Array<AlbumType>>;
    getAllMembers(): Promise<Array<MemberType>>;
    getAllPhotos(): Promise<Array<PhotoType>>;
    getAllPress(): Promise<Array<PressType>>;
    getAllShows(): Promise<Array<ShowType>>;
    getAllSongs(): Promise<Array<SongType>>;
    getAllVideos(): Promise<Array<VideoType>>;
    getMember(id: string): Promise<MemberType>;
    getPhoto(id: string): Promise<PhotoType>;
    getPress(id: string): Promise<PressType>;
    getRelated(entityId: string): Promise<Related>;
    getShow(id: string): Promise<ShowType>;
    getSong(id: string): Promise<SongType>;
    getVideo(id: string): Promise<VideoType>;
    updateAlbum(id: string, title: string, year: bigint, description: string, trackList: Array<string>): Promise<void>;
    updateMember(id: string, name: string, role: string, bio: string, startYear: bigint, endYear: bigint | null): Promise<void>;
    updatePhoto(id: string, title: string, url: string, description: string, year: bigint): Promise<void>;
    updatePress(id: string, title: string, publication: string, date: Time, url: string, excerpt: string): Promise<void>;
    updateShow(id: string, title: string, date: Time, venue: string, city: string, description: string, setlist: Array<string>): Promise<void>;
    updateSong(id: string, title: string, album: string, year: bigint, duration: bigint, lyrics: string, description: string): Promise<void>;
    updateVideo(id: string, title: string, url: string, description: string, year: bigint): Promise<void>;
}
import type { AlbumType as _AlbumType, MemberType as _MemberType, PhotoType as _PhotoType, PressType as _PressType, Related as _Related, RelatedItem as _RelatedItem, RelatedType as _RelatedType, ShowType as _ShowType, SongType as _SongType, VideoType as _VideoType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createAlbum(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlbum(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlbum(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createMember(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMember(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMember(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createPhoto(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPhoto(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPhoto(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createPress(arg0: string, arg1: string, arg2: string, arg3: Time, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPress(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPress(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createShow(arg0: string, arg1: string, arg2: Time, arg3: string, arg4: string, arg5: string, arg6: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createShow(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShow(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createSong(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSong(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSong(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createVideo(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createVideo(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVideo(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteAlbum(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAlbum(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAlbum(arg0);
            return result;
        }
    }
    async deleteMember(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMember(arg0);
            return result;
        }
    }
    async deletePhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePhoto(arg0);
            return result;
        }
    }
    async deletePress(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePress(arg0);
            return result;
        }
    }
    async deleteShow(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShow(arg0);
            return result;
        }
    }
    async deleteSong(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSong(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSong(arg0);
            return result;
        }
    }
    async deleteVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async getAlbum(arg0: string): Promise<AlbumType> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlbum(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlbum(arg0);
            return result;
        }
    }
    async getAllAlbums(): Promise<Array<AlbumType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAlbums();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAlbums();
            return result;
        }
    }
    async getAllMembers(): Promise<Array<MemberType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembers();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembers();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPhotos(): Promise<Array<PhotoType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPhotos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPhotos();
            return result;
        }
    }
    async getAllPress(): Promise<Array<PressType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPress();
            return result;
        }
    }
    async getAllShows(): Promise<Array<ShowType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShows();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShows();
            return result;
        }
    }
    async getAllSongs(): Promise<Array<SongType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSongs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSongs();
            return result;
        }
    }
    async getAllVideos(): Promise<Array<VideoType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideos();
            return result;
        }
    }
    async getMember(arg0: string): Promise<MemberType> {
        if (this.processError) {
            try {
                const result = await this.actor.getMember(arg0);
                return from_candid_MemberType_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMember(arg0);
            return from_candid_MemberType_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhoto(arg0: string): Promise<PhotoType> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhoto(arg0);
            return result;
        }
    }
    async getPress(arg0: string): Promise<PressType> {
        if (this.processError) {
            try {
                const result = await this.actor.getPress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPress(arg0);
            return result;
        }
    }
    async getRelated(arg0: string): Promise<Related> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelated(arg0);
                return from_candid_Related_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelated(arg0);
            return from_candid_Related_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShow(arg0: string): Promise<ShowType> {
        if (this.processError) {
            try {
                const result = await this.actor.getShow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShow(arg0);
            return result;
        }
    }
    async getSong(arg0: string): Promise<SongType> {
        if (this.processError) {
            try {
                const result = await this.actor.getSong(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSong(arg0);
            return result;
        }
    }
    async getVideo(arg0: string): Promise<VideoType> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return result;
        }
    }
    async updateAlbum(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAlbum(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAlbum(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateMember(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMember(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMember(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updatePhoto(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePhoto(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePhoto(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updatePress(arg0: string, arg1: string, arg2: string, arg3: Time, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePress(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePress(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateShow(arg0: string, arg1: string, arg2: Time, arg3: string, arg4: string, arg5: string, arg6: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShow(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShow(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateSong(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSong(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSong(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateVideo(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideo(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideo(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_MemberType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberType): MemberType {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_RelatedItem_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RelatedItem): RelatedItem {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_RelatedType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RelatedType): RelatedType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Related_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Related): Related {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    relatedType: _RelatedType;
}): {
    relatedType: RelatedType;
} {
    return {
        relatedType: from_candid_RelatedType_n12(_uploadFile, _downloadFile, value.relatedType)
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    name: string;
    role: string;
    years: [bigint, [] | [bigint]];
}): {
    id: string;
    bio: string;
    name: string;
    role: string;
    years: [bigint, bigint | null];
} {
    return {
        id: value.id,
        bio: value.bio,
        name: value.name,
        role: value.role,
        years: from_candid_tuple_n5(_uploadFile, _downloadFile, value.years)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    relatedItems: Array<_RelatedItem>;
    relatedType: _RelatedType;
}): {
    id: string;
    relatedItems: Array<RelatedItem>;
    relatedType: RelatedType;
} {
    return {
        id: value.id,
        relatedItems: from_candid_vec_n9(_uploadFile, _downloadFile, value.relatedItems),
        relatedType: from_candid_RelatedType_n12(_uploadFile, _downloadFile, value.relatedType)
    };
}
function from_candid_tuple_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, [] | [bigint]]): [bigint, bigint | null] {
    return [
        value[0],
        from_candid_opt_n6(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    members: Array<_MemberType>;
} | {
    albums: Array<_AlbumType>;
} | {
    shows: Array<_ShowType>;
} | {
    songs: Array<_SongType>;
} | {
    press: Array<_PressType>;
} | {
    videos: Array<_VideoType>;
} | {
    photos: Array<_PhotoType>;
}): {
    __kind__: "members";
    members: Array<MemberType>;
} | {
    __kind__: "albums";
    albums: Array<AlbumType>;
} | {
    __kind__: "shows";
    shows: Array<ShowType>;
} | {
    __kind__: "songs";
    songs: Array<SongType>;
} | {
    __kind__: "press";
    press: Array<PressType>;
} | {
    __kind__: "videos";
    videos: Array<VideoType>;
} | {
    __kind__: "photos";
    photos: Array<PhotoType>;
} {
    return "members" in value ? {
        __kind__: "members",
        members: from_candid_vec_n2(_uploadFile, _downloadFile, value.members)
    } : "albums" in value ? {
        __kind__: "albums",
        albums: value.albums
    } : "shows" in value ? {
        __kind__: "shows",
        shows: value.shows
    } : "songs" in value ? {
        __kind__: "songs",
        songs: value.songs
    } : "press" in value ? {
        __kind__: "press",
        press: value.press
    } : "videos" in value ? {
        __kind__: "videos",
        videos: value.videos
    } : "photos" in value ? {
        __kind__: "photos",
        photos: value.photos
    } : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemberType>): Array<MemberType> {
    return value.map((x)=>from_candid_MemberType_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RelatedItem>): Array<RelatedItem> {
    return value.map((x)=>from_candid_RelatedItem_n10(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
